### ISSUE TITLE
Bug with time out players

### ISSUE THREAD

**Issue by Zemenus** [joshuaprince/CoordinateOffset#11]
**Describe the bug**
So, there is a player who cannot connect

**Environment details**
Output of `/version`: 
```
[23:49:21 INFO]: Current: git-Purpur-2127 (MC: 1.20.4)*
Previous: git-Purpur-2124 (MC: 1.20.4)
* You are 11 version(s) behind
```

CoordinateOffset version: 3.0.2

PacketEvents/ProtocolLib version: 
[23:50:29 INFO]: [ProtocolLib] The updater did not find an update, and nothing was downloaded.
[23:50:29 INFO]: Remote version: 5.1.0
[23:50:29 INFO]: Current version: 5.2.0-SNAPSHOT-679

Output of `/plugins`: 
```
Paper Plugins: (1):
WolfyUtilities
Bukkit Plugins: (37):
AntiPopup, BlueSlimeCore, Chunky, Citizens, CombatLogX, CoordinateOffset, CustomCrafting, dDiscordBot, Denizen, Depenizen, DiscordSRV, FastMinecarts, GSit, ImageFrame, ItemsAdder, Kingdoms, LoneLibs, LPC, LuckPerms, MinimapControl
MMOItems, ModelEngine, MythicCrucible, MythicLib, MythicMobs, ore-control, packetevents, Pl-Hide-Pro, PlaceholderAPI, ProtocolLib
[23:51:13 INFO]:  RoseLoot, SkinsRestorer, spark, TAB, tinylives, Vault, Vulcan
```

**Log errors**
```
[23:46:58 WARN]: [com.github.retrooper.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
java.util.NoSuchElementException: Unknown player for Offset lookup: Igrok_x_xp
        at com.jtprince.coordinateoffset.PlayerOffsetsManager.getPerWorldCacheFor(PlayerOffsetsManager.java:79) ~[CoordinateOffset-v3.0.2.jar:?]
        at com.jtprince.coordinateoffset.PlayerOffsetsManager.getOffset(PlayerOffsetsManager.java:54) ~[CoordinateOffset-v3.0.2.jar:?]
        at com.jtprince.coordinateoffset.PacketOffsetAdapter$Listener.onPacketReceive(PacketOffsetAdapter.java:87) ~[CoordinateOffset-v3.0.2.jar:?]
        at com.github.retrooper.packetevents.event.PacketReceiveEvent.call(PacketReceiveEvent.java:45) ~[packetevents-spigot-2.2.0.jar:?]
        at com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:52) ~[packetevents-spigot-2.2.0.jar:?]
        at com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleServerBoundPacket(PacketEventsImplHelper.java:82) ~[packetevents-spigot-2.2.0.jar:?]
        at io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.read(PacketEventsDecoder.java:51) ~[packetevents-spigot-2.2.0.jar:?]
        at io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:58) ~[packetevents-spigot-2.2.0.jar:?]
        at <snipped>
```
**Steps to reproduce**
This player had a lot of ping

**Comment by joshuaprince** [comment]
It looks like these exceptions are related to receiving packets from players. Can you find out which client mods these players have installed?

Also, this exception should not prevent the players from joining, even if it creates spam in the console. Can they join if CoordinateOffset is removed?

**Comment by joshuaprince** [comment]
If they still can't join even without CoordinateOffset, there's probably some other plugin or setting changing the login process and preventing the logins. I can't provide support for that. Try doing a [binary search](https://docs.papermc.io/paper/basic-troubleshooting#binary-search) and following other troubleshooting guides to figure out which plugin is causing it, and if these errors come back after fixing them and reinstalling CoordinateOffset, feel free to reopen this issue.
