### ISSUE TITLE
Update to 1.20.6

### ISSUE THREAD

**Issue by TheoMarque** [joshuaprince/CoordinateOffset#12]
Generally - need updated to  latest MC version :)
Latest available PacketEvents that are compatible with 1.20.6 packetevents-spigot-2.2.1.jar

[21:42:08 ERROR]: Error occurred while enabling CoordinateOffset v3.0.2 (Is it up to date?)
com.jtprince.lib.dev.jorel.commandapi.exceptions.UnsupportedVersionException: This version of Minecraft is unsupported: 1.20.6
        at CoordinateOffset-v3.0.2.jar/com.jtprince.lib.dev.jorel.commandapi.CommandAPIVersionHandler.getPlatform(CommandAPIVersionHandler.java:73) ~[CoordinateOffset-v3.0.2.jar:?]
        at CoordinateOffset-v3.0.2.jar/com.jtprince.lib.dev.jorel.commandapi.CommandAPI.onLoad(CommandAPI.java:103) ~[CoordinateOffset-v3.0.2.jar:?]
        at CoordinateOffset-v3.0.2.jar/com.jtprince.coordinateoffset.CoordinateOffset.onEnable(CoordinateOffset.java:31) ~[CoordinateOffset-v3.0.2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:git-Paper-51]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:git-Paper-51]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.6.jar:git-Paper-51]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.6.jar:git-Paper-51]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:682) ~[paper-1.20.6.jar:git-Paper-51]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:441) ~[paper-1.20.6.jar:git-Paper-51]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:324) ~[paper-1.20.6.jar:git-Paper-51]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1140) ~[paper-1.20.6.jar:git-Paper-51]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.6.jar:git-Paper-51]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]

**Comment by joshuaprince** [comment]
Support added for 1.20.5-1.20.6 in [v3.1.0](https://github.com/joshuaprince/CoordinateOffset/releases/tag/v3.1.0). Be sure to update to PacketEvents [dev build](https://ci.codemc.io/job/retrooper/job/packetevents/) #397 or above.
